#Default port is 8761
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false            # Don't register with Eureka service
    fetchRegistry: false                 # Don't cache registry information locally
  server:
    waitTimeInMsWhenSyncEmpty: 5         # Initial time to wait before server takes requests
  serviceUrl:
    defaultZone: http://localhost:8761

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
