example.property: "The prod configuration"
spring.jpa.database: "MYSQL"
spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3306/test?useSSL=true"
spring.datasource.username: "root"
spring.datasource.password: "{cipher}8e2e38b0e293fb4c0a8def88b828a8b2a6d1f5984ebbdedc0a6dd54ff355dd86"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5Dialect"
signing.key: "345345fsdfsf5345"                   # The symmetrical key for generating JWT token